window.TRANSLATIONS = {
  id: {
    skipLink: "Lewati ke konten utama",
    navAria: "Navigasi utama",
    brandAria: "Kembali ke beranda",
    menuOpen: "Buka menu",
    menuClose: "Tutup menu",
    navAbout: "Tentang",
    navSkills: "Keahlian",
    navEducation: "Pendidikan",
    navProjects: "Proyek",
    navContact: "Kontak",
    themeAria: "Ganti tema tampilan",
    langAria: "Ganti bahasa",

    availability: "Terbuka untuk belajar, berdiskusi, dan berkolaborasi",
    eyebrow: "Halo, saya",
    rolePrefix: "Seorang",
    heroDesc: "Saya senang membangun sesuatu di pertemuan antara perangkat keras dan perangkat lunak: embedded system, pemrosesan audio digital, elektronika, Linux, dan eksperimen Android.",
    heroBtn: "Lihat proyek",
    factsAria: "Informasi singkat",
    location: "Indonesia",
    status: "Mahasiswa Teknik Elektro",

    profileAlt: "Foto profil REITZG",
    profileStatus: "Aktif belajar dan bereksperimen",
    profileMetrics1: "Hardware + Software",
    profileMetrics2: "Belajar lewat proyek",

    aboutEyebrow: "01 / Tentang saya",
    aboutTitle: "Mengenal saya lebih dekat",
    aboutDesc: "Saya menikmati proses memahami cara kerja teknologi hingga ke lapisan yang paling dasar.",
    aboutP1: "Saya adalah mahasiswa Teknik Elektro dari Universitas Tidar. Ketertarikan saya tidak berhenti pada teori rangkaian; saya juga suka mengubah ide menjadi program, prototipe, dan eksperimen yang benar-benar dapat diuji.",
    aboutP2: "Saat ini fokus saya banyak berada pada <strong>embedded system</strong>, <strong>audio DSP</strong>, pemrograman C/C++, perangkat berbasis ESP32 dan Arduino, serta eksploitasi sistem Linux dan Android. Saya menyukai solusi yang efisien, dapat dipahami, dan memiliki tujuan nyata.",
    aboutQuote: "\u201CTeknologi terbaik bukan hanya yang terlihat canggih, tetapi yang bekerja dengan efisien dan dapat dipahami.\u201D",

    highlight1Title: "Problem Solver",
    highlight1Desc: "Menelusuri masalah dari gejala, menguji kemungkinan, lalu membangun solusi yang masuk akal.",
    highlight2Title: "Hands-on Learner",
    highlight2Desc: "Belajar melalui eksperimen langsung, pengukuran, debugging, dan penyempurnaan bertahap.",
    highlight3Title: "Curious Engineer",
    highlight3Desc: "Tertarik memahami hubungan antara kode, sistem operasi, elektronik, dan performa perangkat.",

    skillsEyebrow: "02 / Keahlian",
    skillsTitle: "Teknologi yang saya pelajari dan gunakan",
    skillsDesc: "Keahlian saya berkembang melalui perkuliahan, proyek mandiri, dan eksperimen teknis.",

    eduEyebrow: "03 / Pendidikan & fokus",
    eduTitle: "Perjalanan belajar",
    eduDesc: "Pendidikan formal menjadi fondasi, sementara proyek mandiri memperluas cara saya berpikir.",
    eduCurrent: "Saat ini",
    eduEducation: "Pendidikan",
    eduProdi: "Program Studi Teknik Elektro",
    eduActive: "Mahasiswa aktif",
    eduProdiDesc: "Mempelajari dasar kelistrikan, elektronika, pemrograman, sistem digital, rangkaian, instrumentasi, serta penerapannya pada perangkat modern.",
    eduOngoing: "Berkelanjutan",
    eduSelf: "Mandiri",
    eduSelfTitle: "Eksperimen Embedded, Linux & Android",
    eduSelfSub: "Self-directed learning",
    eduSelfDesc: "Mengembangkan proyek ESP32, mempelajari audio digital, menjalankan Linux ARM, mencoba custom ROM, serta menganalisis performa dan stabilitas perangkat.",
    focusLabel: "Fokus sekarang",
    focusTitle: "Apa yang sedang saya dalami?",
    focus1: "Real-time audio processing pada mikrokontroler",
    focus2: "Integrasi sensor, ADC, DAC, dan protokol I\u00B2S",
    focus3: "Optimasi program C/C++ untuk embedded system",
    focus4: "Linux ARM, kernel, driver grafis, dan Android",

    projEyebrow: "04 / Proyek pilihan",
    projTitle: "Beberapa hal yang saya bangun",
    projDesc: "Proyek yang menggabungkan pemrograman, elektronika, dan rasa ingin tahu.",
    projAll: "Semua repositori",
    projMissing: "Dokumentasi akan ditambahkan",

    contactEyebrow: "05 / Mari terhubung",
    contactTitle: "Punya ide, proyek, atau topik teknis yang menarik?",
    contactDesc: "Saya terbuka untuk berdiskusi, bertukar pengetahuan, dan berkolaborasi dalam proyek embedded system, elektronika, perangkat lunak, maupun open source.",
    contactBtn: "Kunjungi GitHub",
    backToTop: "Kembali ke atas",

    footerBuilt: "Dibangun dengan HTML, CSS, JavaScript, dan rasa ingin tahu."
  },

  en: {
    skipLink: "Skip to main content",
    navAria: "Main navigation",
    brandAria: "Back to homepage",
    menuOpen: "Open menu",
    menuClose: "Close menu",
    navAbout: "About",
    navSkills: "Skills",
    navEducation: "Education",
    navProjects: "Projects",
    navContact: "Contact",
    themeAria: "Toggle theme",
    langAria: "Switch language",

    availability: "Open to learn, discuss, and collaborate",
    eyebrow: "Hello, I'm",
    rolePrefix: "A",
    heroDesc: "I enjoy building things at the intersection of hardware and software: embedded systems, digital audio processing, electronics, Linux, and Android experimentation.",
    heroBtn: "View projects",
    factsAria: "Quick facts",
    location: "Indonesia",
    status: "Electrical Engineering Student",

    profileAlt: "REITZG profile photo",
    profileStatus: "Active learning and experimenting",
    profileMetrics1: "Hardware + Software",
    profileMetrics2: "Learning through projects",

    aboutEyebrow: "01 / About me",
    aboutTitle: "Get to know me closer",
    aboutDesc: "I enjoy the process of understanding how technology works down to its deepest layers.",
    aboutP1: "I am an Electrical Engineering student from Universitas Tidar. My interest doesn't stop at circuit theory; I also love turning ideas into programs, prototypes, and experiments that can actually be tested.",
    aboutP2: "Currently, my focus is on <strong>embedded systems</strong>, <strong>audio DSP</strong>, C/C++ programming, ESP32 and Arduino-based devices, as well as Linux and Android exploitation. I prefer efficient, understandable solutions with real purpose.",
    aboutQuote: "\u201CThe best technology is not just sophisticated, but one that works efficiently and can be understood.\u201D",

    highlight1Title: "Problem Solver",
    highlight1Desc: "Tracing issues from symptoms, testing possibilities, then building reasonable solutions.",
    highlight2Title: "Hands-on Learner",
    highlight2Desc: "Learning through direct experimentation, measurement, debugging, and gradual refinement.",
    highlight3Title: "Curious Engineer",
    highlight3Desc: "Interested in understanding the relationship between code, operating systems, electronics, and device performance.",

    skillsEyebrow: "02 / Skills",
    skillsTitle: "Technologies I learn and use",
    skillsDesc: "My skills develop through coursework, personal projects, and technical experimentation.",

    eduEyebrow: "03 / Education & focus",
    eduTitle: "Learning journey",
    eduDesc: "Formal education is my foundation, while personal projects broaden my way of thinking.",
    eduCurrent: "Current",
    eduEducation: "Education",
    eduProdi: "Electrical Engineering Study Program",
    eduActive: "Active student",
    eduProdiDesc: "Learning fundamentals of electrical engineering, electronics, programming, digital systems, circuits, instrumentation, and their application in modern devices.",
    eduOngoing: "Ongoing",
    eduSelf: "Self-study",
    eduSelfTitle: "Embedded, Linux & Android Experiments",
    eduSelfSub: "Self-directed learning",
    eduSelfDesc: "Developing ESP32 projects, learning digital audio, running Linux ARM, trying custom ROMs, and analyzing device performance and stability.",
    focusLabel: "Current focus",
    focusTitle: "What am I diving into?",
    focus1: "Real-time audio processing on microcontrollers",
    focus2: "Sensor, ADC, DAC, and I\u00B2S protocol integration",
    focus3: "C/C++ program optimization for embedded systems",
    focus4: "Linux ARM, kernel, graphics drivers, and Android",

    projEyebrow: "04 / Featured projects",
    projTitle: "Some things I've built",
    projDesc: "Projects that combine programming, electronics, and curiosity.",
    projAll: "All repositories",
    projMissing: "Documentation coming soon",

    contactEyebrow: "05 / Let's connect",
    contactTitle: "Have an idea, project, or interesting technical topic?",
    contactDesc: "I'm open to discuss, exchange knowledge, and collaborate on embedded systems, electronics, software, and open source projects.",
    contactBtn: "Visit GitHub",
    backToTop: "Back to top",

    footerBuilt: "Built with HTML, CSS, JavaScript, and curiosity."
  }
};
